# ====================================================
# ユーティリティ
# ====================================================
[[plugins]]  # deno: 次世代暗黒系プラグラインの前提になりそう
repo = 'vim-denops/denops.vim'

[[plugins]]  # プラグイン管理
repo = 'Shougo/dein.vim'
hook_add = '''
  let g:dein#types#git#clone_depth = 1
'''

[[plugins]]  # 非同期処理
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # ファイルタイプの動的決定
repo = 'Shougo/context_filetype.vim'
hook_add = '''
  let g:context_filetype#filetypes = {
  \ 'toml': [
  \   {
  \     'filetype':'vim',
  \     'start': '\v^hook_(add|source|post_source)\s\=\s'."'+$",
  \     'end': "\v^'{3}$"
  \   },
  \ ],
  \ 'python': [
  \   {
  \     'filetype': 'rst',
  \     'start': '""".*\.$',
  \     'end': '^\s*"""$'
  \   }
  \ ],
  \}
  let g:context_filetype#search_offset = 100
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'

[[plugins]] # git 表示
repo = "airblade/vim-gitgutter"

[[plugins]] # git 操作
repo = "tpope/vim-fugitive"

[[plugins]]  # truble.vim の依存
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]  # truble.vim の依存
repo = 'folke/lsp-colors.nvim'

# ====================================================
# 編集支援
# ====================================================
[[plugins]] # 日付情報の自動更新
repo = 'vim-scripts/autodate.vim'

[[plugins]] # スニペットの基本セット
repo = 'Shougo/neosnippet-snippets'

[[plugins]]  # AIRLINE Theme
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # カッコ制御
repo = 'kana/vim-smartinput'

[[plugins]] # 囲み制御
repo = 'rhysd/vim-operator-surround'
hook_add = '''
  map <silent>sa <Plug>(operator-surround-append)
  map <silent>sd <Plug>(operator-surround-delete)
  map <silent>sr <Plug>(operator-surround-replace)
  nmap <Leader><Leader>w bvwhsa
'''

[[plugins]] # 置換制御
repo = 'osyo-manga/vim-over'
hook_add = '''
  nnoremap <silent> <Space>o :OverCommandLine<CR>%s//g<Left><Left>
  vnoremap <silent> <Space>o :OverCommandLine<CR>s//g<Left><Left>
  nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>
'''

# ====================================================
# Text Object 管理
# ====================================================
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'

# ============================================
# selector
# ============================================
[[plugins]]
 repo = 'junegunn/fzf'
 merged = 0
 build = '''
 ./install --all
'''

[[plugins]]
 repo = 'junegunn/fzf.vim'
 hook_add = '''
 nnoremap <silent> <Leader>. :<C-u>FZFFileList<CR>
 nnoremap <silent> <Leader>, :<C-u>FZFMru<CR>
 nnoremap <silent> <Leader>l :<C-u>Lines<CR>
 nnoremap <silent> <Leader>b :<C-u>Buffers<CR>
 nnoremap <silent> <Leader>k :<C-u>Rg<CR>
 command! FZFFileList call fzf#run({
            \ 'source': 'rg --files --hidden',
            \ 'sink': 'e',
            \ 'options': '-m --border=none',
            \ 'down': '20%'})
 command! FZFMru call fzf#run({
            \ 'source': v:oldfiles,
            \ 'sink': 'e',
            \ 'options': '-m +s --border=none',
            \ 'down':  '20%'})

 let g:fzf_layout = {'up':'~90%', 'window': { 'width': 0.8, 'height': 0.8,'yoffset':0.5,'xoffset': 0.5, 'border': 'none' } }

 augroup vimrc_fzf
 autocmd!
 autocmd FileType fzf tnoremap <silent> <buffer> <Esc> <C-g>
 autocmd FileType fzf set laststatus=0 noshowmode noruler
      \| autocmd BufLeave <buffer> set laststatus=2 noshowmode ruler
 augroup END

 function! RipgrepFzf(query, fullscreen)
    let command_fmt = 'rg --column --hiddden --line-number --no-heading --color=always --smart-case %s || true'
    let initial_command = printf(command_fmt, shellescape(a:query))
    let reload_command = printf(command_fmt, '{q}')
    let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
    call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
 endfunction

 command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)
'''


# ============================================
# file type / syntax の追加
# ============================================
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # typescript
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]  # vue
repo = 'posva/vim-vue'

[[plugins]]  # json
repo = 'elzr/vim-json'

[[plugins]] # Colour Shceme
repo = 'jacoborus/tender.vim'
hook_add = '''
  au MyAutoCmd VimEnter * nested colorscheme tender
'''
