# ====================================================
# ユーティリティ
# ====================================================
[[plugins]]  # プラグイン管理
repo = 'Shougo/dein.vim'

[[plugins]]  # vim interface framework
repo = 'Shougo/denite.nvim'
hook_add = '''
   call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
   call denite#custom#var('grep', 'command', ['ag'])
   call denite#custom#var('grep', 'recursive_opts', [])
   call denite#custom#var('grep', 'pattern_opt', [])
   call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''

[[plugins]]  # 非同期処理
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # ファイルタイプの動的決定
repo = 'Shougo/context_filetype.vim'
hook_add = '''
  let g:context_filetype#filetypes = {
  \ 'toml': [
  \   {
  \     'filetype':'vim',
  \     'start': '\v^hook_(add|source|post_source)\s\=\s'."'+$",
  \     'end': "\v^'{3}$"
  \   },
  \ ],
  \ 'python': [
  \   {
  \     'filetype': 'rst',
  \     'start': '""".*\.$',
  \     'end': '^\s*"""$'
  \   }
  \ ],
  \}
  let g:context_filetype#search_offset = 100
'''

[[plugins]] # git 表示
repo = "airblade/vim-gitgutter"

[[plugins]] # git 操作
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'glacambre/firenvim'
hook_add = '''
let g:firenvim_config = {
\  'localSettings': {
\    '.*': {
\      'selector': 'textarea, div[role="textbox"]',
\      'priority': 0,
\    },
\    'github\.com': {
\      'selector': 'textarea',
\      'priority': 1,
\    },
\  }
\}
'''
hook_post_update = '''
  call firenvim#install(0)
'''
# ====================================================
# 編集支援
# ====================================================
[[plugins]] # スニペットの基本セット
repo = 'Shougo/neosnippet-snippets'

[[plugins]]  # AIRLINE Theme
repo = 'vim-airline/vim-airline-themes'

[[plugins]] # カッコ制御
repo = 'kana/vim-smartinput'

[[plugins]] # 囲み制御
repo = 'rhysd/vim-operator-surround'
hook_add = '''
  map <silent>sa <Plug>(operator-surround-append)
  map <silent>sd <Plug>(operator-surround-delete)
  map <silent>sr <Plug>(operator-surround-replace)
  nmap <Leader><Leader>w bvwhsa
'''

[[plugins]] # 置換制御
repo = 'osyo-manga/vim-over'
hook_add = '''
  nnoremap <silent> <Space>o :OverCommandLine<CR>%s//g<Left><Left>
  vnoremap <silent> <Space>o :OverCommandLine<CR>s//g<Left><Left>
  nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>
'''
# Ctags
# --------------------------------------------------

[[plugins]]
# this plugins is require global
# Run `sudo apt install global`
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
  let g:gen_tags#ctags_auto_gen = 1
'''


[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  nmap <Leader>t :TagbarToggle<CR>
'''

# 英語支援
# --------------------------------------------------
[[plugins]]
repo = 'qh73xe/nvim-trans'

[[plugins]] # vimからlookコマンドを使用する
repo = 'ujihisa/neco-look'


# ====================================================
# Text Object 管理
# ====================================================
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'


# ============================================
# file type / syntax の追加
# ============================================
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # typescript
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]  # vue
repo = 'posva/vim-vue'

[[plugins]]  # json
repo = 'elzr/vim-json'
