# ====================================================
# ユーティリティ
# ====================================================
[[plugins]]  # プラグイン管理
repo = 'Shougo/dein.vim'

[[plugins]]  # vim interface framework
repo = 'Shougo/denite.nvim'
hook_add = '''
   call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
   call denite#custom#var('grep', 'command', ['ag'])
   call denite#custom#var('grep', 'recursive_opts', [])
   call denite#custom#var('grep', 'pattern_opt', [])
   call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''

[[plugins]]  # 非同期処理
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # ファイルタイプの動的決定
repo = 'Shougo/context_filetype.vim'
hook_add = '''
  let g:context_filetype#filetypes = {
  \ 'toml': [
  \   {
  \     'filetype':'vim',
  \     'start': '\v^hook_(add|source|post_source)\s\=\s'."'+$",
  \     'end': "\v^'{3}$"
  \   },
  \ ],
  \ 'python': [
  \   {
  \     'filetype': 'rst',
  \     'start': '""".*\.$',
  \     'end': '^\s*"""$'
  \   }
  \ ],
  \}
  let g:context_filetype#search_offset = 100
'''

[[plugins]] # git 表示
repo = "airblade/vim-gitgutter"

[[plugins]] # git 操作
repo = "tpope/vim-fugitive"


# ====================================================
# 編集支援
# ====================================================
[[plugins]] # スニペットの基本セット
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # スニペット管理
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
hook_add = '''
  let g:neosnippet#enable_snipmate_compatibility = 1
  let g:neosnippet#snippets_directory=g:ECT_DIR . '/snipets/'
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> "<Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?  "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
'''

[[plugins]]  # 補完
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" : neosnippet#expandable_or_jumpable() ? "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''

[[plugins]] # カッコ制御
repo = 'kana/vim-smartinput'

[[plugins]] # 囲み制御
repo = 'rhysd/vim-operator-surround'
hook_add = '''
  map <silent>sa <Plug>(operator-surround-append)
  map <silent>sd <Plug>(operator-surround-delete)
  map <silent>sr <Plug>(operator-surround-replace)
  nmap <Leader><Leader>w bvwhsa
'''

[[plugins]] # 置換制御
repo = 'osyo-manga/vim-over'
hook_add = '''
  nnoremap <silent> <Space>o :OverCommandLine<CR>%s//g<Left><Left>
  vnoremap <silent> <Space>o :OverCommandLine<CR>s//g<Left><Left>
  nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>
'''
# Ctags
# --------------------------------------------------

[[plugins]]
# this plugins is require global
# Run `sudo apt install global`
repo = 'jsfaint/gen_tags.vim'
hook_add = '''
  let g:gen_tags#ctags_auto_gen = 1
'''


[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  nmap <Leader>t :TagbarToggle<CR>
'''

[[plugins]]
repo = 'fuenor/im_control.vim'
hook_add = '''
  set timeout timeoutlen=3000 ttimeoutlen=100
  set formatoptions+=mM
  set spelllang=en,cjk
  set ambiwidth=double

  let IM_CtrlMode = 1
  inoremap <silent> <C-j> <C-r>=IMState('FixMode')<CR>
  function! IMCtrl(cmd)
    let cmd = a:cmd
    if cmd == 'On'
      let res = system('ibus engine kkc')
    elseif cmd == 'Off'
      let res = system('xkb:us::eng')
      " let res = system('xkb:jp::jpn')
    endif
    return ''
  endfunction
  set cmdheight=2
'''

# 英語支援
# --------------------------------------------------
[[plugins]]
repo = 'qh73xe/nvim-trans'

[[plugins]] # vimからlookコマンドを使用する
repo = 'ujihisa/neco-look'


# ====================================================
# Text Object 管理
# ====================================================
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-function'


# ============================================
# file type / syntax の追加
# ============================================
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # typescript
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]  # vue
repo = 'posva/vim-vue'

# ====================================================
# UI 制御
# ====================================================
[[plugins]]  # AIRLINE Theme
repo = 'vim-airline/vim-airline-themes'

[[plugins]]  # AIRLINE
repo = 'vim-airline/vim-airline'
hook_add = '''
  set laststatus=2
  let g:airline_powerline_fonts = 1

  " tab 設定
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
  nmap <C-p> <Plug>AirlineSelectPrevTab
  nmap <C-n> <Plug>AirlineSelectNextTab

  " レイアウト
'''

[[plugins]] # Colour Shceme
repo = 'jacoborus/tender.vim'
hook_add = '''
  set termguicolors
  set background=dark
  let g:airline_theme = 'tender'
  au MyAutoCmd VimEnter * nested colorscheme tender
'''

[[plugins]]  # Indent 表示
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
  au MyAutoCmd FileType *.html nested setlocal tabstop=2 softtabstop=2 shiftwidth=2
  au MyAutoCmd FileType *.rst nested setlocal tabstop=3 softtabstop=3 shiftwidth=3
  au MyAutoCmd FileType *.js nested setlocal tabstop=2 softtabstop=2 shiftwidth=2
  au MyAutoCmd FileType *.toml nested setlocal tabstop=2 softtabstop=2 shiftwidth=2
  au MyAutoCmd FileType *.vim nested setlocal tabstop=2 softtabstop=2 shiftwidth=2
  au MyAutoCmd FileType *.vue nested setlocal tabstop=2 softtabstop=2 shiftwidth=2
  au MyAutoCmd VimEnter * nested :hi IndentGuidesOdd  guibg=DarkGrey ctermbg=DarkGrey
  au MyAutoCmd VimEnter * nested :hi IndentGuidesEven guibg=#73cef4 ctermbg=81
'''
